name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

    paths:
      - frontend/**
      - .github/workflows/frontend-unit-tests.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: frontend/.node-version
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Lint code
        run: npm run lint
        working-directory: frontend

      - name: Type check
        run: npm run type-check
        working-directory: frontend

      - name: Run tests
        run: npm run test
        working-directory: frontend

      - name: Build project
        run: npm run build

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: path/to/test-results
